# Generated by Django 3.0.5 on 2020-04-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_xiangce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='xiangce',
            name='fenlei',
            field=models.CharField(default='1', max_length=50, verbose_name='分类'),
        ),
    ]
