# Generated by Django 3.0.5 on 2020-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200418_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xiangce',
            name='fenlei',
            field=models.CharField(blank=True, default='1', max_length=50, verbose_name='分类'),
        ),
    ]
